# Generated by Django 5.2.1 on 2025-07-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projectconfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(db_column='key', max_length=64)),
                ('value', models.CharField(db_column='value', default='', max_length=11)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('memo', models.TextField()),
            ],
        ),
    ]
