# Generated by Django 4.2 on 2025-09-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_func', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectconfig',
            name='value',
            field=models.CharField(db_column='value', default='', max_length=255),
        ),
    ]
